### ISSUE TITLE
Add support for 22.04

### ISSUE THREAD

**Issue by fakhamatia** [Sispheor/indicator-ip#15]

**Comment by Sispheor** [comment]
Sorry but I won't. I only support the last Ubuntu LTS.

**Comment by fakhamatia** [comment]
What's about Ubuntu 22.04 LTS ?

**Comment by Sispheor** [comment]
I'll start working on it. Next weekend I think. I finishing another project first.

**Comment by Sispheor** [comment]
Package updated on Ubuntu 22.04.

**Comment by fakhamatia** [comment]
```
$ indicator-ip
Traceback (most recent call last):
  File "/usr/bin/indicator-ip", line 33, in <module>
    sys.exit(load_entry_point('indicator-ip==1.2.5', 'console_scripts', 'indicator-ip')())
  File "/usr/bin/indicator-ip", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/indicator_ip/__init__.py", line 6, in <module>
    from indicator_ip.indicator_ip_menu import IndicatorIPMenu
  File "/usr/lib/python3/dist-packages/indicator_ip/indicator_ip_menu.py", line 10, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available
```

**Comment by Sispheor** [comment]
Humm,
Could you test:
```
sudo apt install gir1.2-appindicator3-0.1
```

Should be brought by the installer...

**Comment by gripfastistech** [comment]
Ubuntu Mate 23.10 here. 

For anyone who is slightly ahead the LTS, changing the release name from mantic (23.10) in the apt sources filename and inside the ppa file to jammy (22.04), then installing gir1.2-appindicator3-0.1, works perfectly.

Thank you @Sispheor !
